[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist/image-creation"
[build.environment]
  NODE_VERSION = "18.13"
[functions]
  node_bundler = "esbuild"
[[redirects]]
from = "/*"
to = "index.html"
status = 200